<COMMENT>
CREATE TRIGGER <VAL_NETWOK_NAME>_arc_arc_trigger
  AFTER INSERT OR UPDATE OR DELETE ON <ARC_TABLE_NAME>
  FOR EACH STATEMENT
  EXECUTE PROCEDURE ast_arcarcnetwork('<ARC_TABLE_NAME>', 'geom');
  
  